# Generated by Django 3.2 on 2021-04-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210424_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
